### ISSUE TITLE
error in npm install under server dir.

### ISSUE THREAD

**Issue by ravinayag** [IBM/fabric-contract-attribute-based-access-control#16]
Hello, Thank you for sharing this code for learners.

I'm deploying this package under fabricsamples/basicnetwork.  
There is lot of errors while do npm install under Server folder,,  specific while installing  grpc packages and download error and compile errors.
Ignored and started to service by runnnng node server.js,  and ended with below errors. 

Note :1,  I'm not using VSC code extension for this.
2,  Ubuntu 18 vm
3,  npm -v
      6.14.4
4, node -v
     v12.16.3
5. fabric versions 1.4.4

/application/server$ node server.js
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'fabric-ca-client'
Require stack:
- /opt/ksbc/fcabac/application/server/utils.js
- /opt/ksbc/fcabac/application/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/opt/ksbc/fcabac/application/server/utils.js:12:26)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/ksbc/fcabac/application/server/utils.js',
    '/opt/ksbc/fcabac/application/server/server.js'
  ]
}

**Comment by cyamac1993** [comment]
you can change the version of your node to the v8.x in my case 8.17.0 solved the problem.

**Comment by ElangSBP** [comment]
I Recommend to use the IBM Blockchain Platform VSCode Extension code to prevent the problem occured, like mentioned before by @cyamac1993 try to change the node to version 8, to make it easier switching between node version I recommend to use NVM if you still don't use it.

From the error you mentioned the fabric-ca-client still don't properly installed. 

The Basic-Network is not updated again by Hyperledger Fabric Developers try to use test-network, but I still don't test the compatibility of this code into newest Fabric 2.0 I think we need to upgrade the ChainCode first but from what I read in the documentation it's still possible to use it without changing the code, but without the latest function available.

**Comment by ravinayag** [comment]
Thanks  @ElangSBP  @cyamac1993 

I was able to  fix the fabric-ca-client by manuall  install ```npm install fabric-ca-client@1.4.0```
Post to that, I did a small  update to MSPID corrections to address my MSPID in server/utils.js for admin user creation 
 ```var identity = X509WalletMixin.createIdentity('Org1MSP', enrollment.certificate, enrollment.key.toBytes());```

Rest everything works perfect.   A  awesome learning.
